# The resource always writes the complete settings object back: it reads the
# settings of the instance immediately before each write and overlays only the
# attributes below on top of them, the same way the Pritunl web console does.
# `PUT /settings` is a full replace and not a partial update, so applying this
# resource leaves the SMTP, monitoring and every other unmanaged setting of the
# instance untouched.
#
# The settings of a Pritunl instance are a singleton, so the resources below are
# alternatives rather than a configuration to apply as a whole: a given instance
# is managed by a single pritunl_settings resource, carrying all the attributes
# that instance is meant to have.

# Rotating the TLS certificate served by the Pritunl web console and API from a
# certificate stored in Azure Key Vault.
#
# This is the recommended way to source the pair: the azurerm provider parses
# the PKCS12 bundle natively and exposes plain PEM, so `pem` and `key` are
# passed straight through. Pritunl expects raw PEM strings, so unlike the
# Imperva/Incapsula modules they must not be base64 encoded.

data "azurerm_key_vault" "example" {
  name                = "examplekv"
  resource_group_name = "some-resource-group"
}

data "azurerm_key_vault_certificate_data" "example" {
  name         = "my-cert-name"
  key_vault_id = data.azurerm_key_vault.example.id
}

resource "pritunl_settings" "main" {
  server_cert = data.azurerm_key_vault_certificate_data.example.pem
  server_key  = data.azurerm_key_vault_certificate_data.example.key
}

# `pem` holds every certificate of the bundle, `certificates_count` tells how
# many. Should the bundle also carry the root CA, keep the leaf and the
# intermediate(s) only and drop it, clients already trust it through their own
# trust store:
#
#   locals {
#     certificate_blocks = regexall(
#       "-----BEGIN CERTIFICATE-----[^-]+-----END CERTIFICATE-----",
#       data.azurerm_key_vault_certificate_data.example.pem,
#     )
#
#     server_cert = join("\n", slice(local.certificate_blocks, 0, 2))
#   }

# Building the value from a PKCS12 bundle any other way, for instance from a
# local file or an `external` data source shelling out to
# `openssl pkcs12 -nokeys -legacy`, needs that same clean up: the OpenSSL CLI
# writes "Bag Attributes", "subject=" and "issuer=" lines in front of every
# certificate, which are not part of the PEM format and which Pritunl rejects.
# The regexall above removes them, and so does this pipeline:
#
#   openssl pkcs12 -in vpn.pfx -nokeys -legacy |
#     sed -n '/BEGIN CERTIFICATE/,/END CERTIFICATE/p' |
#     awk '/BEGIN CERTIFICATE/ { n++ } n <= 2' > server_cert.pem

# Rotating the TLS certificate from AWS Secrets Manager, which stores a JSON
# secret containing the PEM-encoded certificate and private key. Secrets Manager
# is preferred over ACM in this case because ACM does not export private keys
# for certificates it issues or manages; storing a PEM pair in Secrets Manager
# gives explicit control over the pair's lifecycle and works seamlessly with
# Terraform.

data "aws_secretsmanager_secret_version" "tls" {
  secret_id = "pritunl-tls-cert"
}

locals {
  # Parse the JSON secret containing cert and key.
  # Adjust the field names to match your secret structure.
  tls_secret = jsondecode(data.aws_secretsmanager_secret_version.tls.secret_string)
}

resource "pritunl_settings" "aws" {
  server_cert = local.tls_secret.certificate
  server_key  = local.tls_secret.private_key
}

# The PEM-encoded values fetched from Secrets Manager must already be clean:
# no `Bag Attributes`, `subject=`, or `issuer=` lines, and no root CA. If the
# secret was generated by an external tool (e.g., `openssl pkcs12 -nokeys`),
# scrub it with sed or regexall before storing it.

# Rotating the TLS certificate from local PEM files on disk. This is the
# simplest option for on-premises or development setups without a cloud
# secrets manager.

resource "pritunl_settings" "local_files" {
  server_cert = file("${path.module}/certs/server.pem")
  server_key  = file("${path.module}/certs/server.key")
}

# Files must contain pure PEM: no root CA, no Bag Attributes, no extra text.
# Treat server_key as sensitive: keep the file out of version control and
# restrict its permissions (e.g., chmod 600).

# Managing only the port, on an instance whose certificate is handled elsewhere.
# The certificate already installed is read back and handed over untouched, so
# this never takes ownership of it:
#
#   resource "pritunl_settings" "port_only" {
#     server_port = 8443
#   }
#
# Changing the port makes Pritunl restart its web server on the new one, so the
# `url` of the provider has to be updated before the next run.

# The instance wide toggles and the pin mode. Every attribute left out of the
# configuration is read back from the instance and handed over unchanged, so
# this only ever moves the settings it mentions:

resource "pritunl_settings" "toggles" {
  pin_mode         = "required"
  ipv6             = true
  restrict_import  = true
  client_reconnect = true

  # The two authentication caches are two different settings with deceptively
  # similar names, and both are managed here:
  #
  #   sso_cache        an 8 hour cache keyed on the client id, the IP and the
  #                    MAC address, supported by every OpenVPN client
  #   sso_client_cache a 7 day cache kept as a token on the client itself, only
  #                    supported by the Pritunl client
  sso_cache        = false
  sso_client_cache = true
}

# Okta single sign-on. Okta is a SAML integration on this side of the API, which
# is why the configuration carries both the SAML settings of the identity
# provider and the Okta ones. The whole of it travels together on every write:
# Pritunl clears every single sign-on credential it holds as soon as it is
# handed a blank provider, and rejects a provider that comes without an
# organization or a domain. The organization is referenced by id, which is what
# makes it natural to manage next to it.

resource "pritunl_organization" "sso" {
  name = "sso"
}

resource "pritunl_settings" "sso" {
  sso            = "saml_okta"
  sso_org        = pritunl_organization.sso.id
  server_sso_url = "https://vpn.example.com"

  # from the SAML setup of the Okta application
  sso_saml_url        = "https://example.okta.com/app/pritunl/exampleappid/sso/saml"
  sso_saml_issuer_url = "https://www.okta.com/exampleappid"
  sso_saml_cert       = file("${path.module}/certs/okta-saml.pem")

  # the Okta side of it: the app id is optional, Pritunl only needs it to check
  # that a user is still attached to the application on every VPN connection
  sso_okta_app_id = "0oaexampleappid"
  sso_okta_token  = var.okta_api_token

  # the secondary factor Okta asks for: "passcode", "push", "push_none" for a
  # push whenever the user has a device that takes one, or "" for none at all
  sso_okta_mode = "push"
}

# The web console offers "Okta + Duo Security" and "Okta + Yubico" next to
# "Okta", the same integration with a second factor bolted on, which this
# resource does not support: they need credentials it does not manage.
#
# Pritunl only takes `sso_okta_mode` over while `sso` is exactly `saml_okta`, it
# drops the setting for every other provider, which is why every Okta attribute
# above is required with `sso`.
#
# Single sign-on is never turned off by this resource: dropping `sso` from the
# configuration keeps what the instance has, and destroying the resource keeps
# it as well, since handing Pritunl a blank provider would take the credentials
# of the instance down with it. It is disabled from the web console instead, and
# the next plan then reports it as a drift from the configuration.
#
# `server_sso_url`, `sso_saml_url` and `sso_saml_issuer_url` are normalised by
# recent Pritunl versions, which add the `https://` scheme when the value
# carries none and lowercase the host, so they are best configured already
# normalised: a value Pritunl rewrites reads back differently from the
# configured one and leaves a plan that never settles.
